In [26]:
import numpy as np
import cv2

In [27]:
cv2.__version__

'4.1.1'

In [7]:
img = cv2.imread('opencv-logo.png',1)   # 1 is for original colours
# 0 is for getting a black and white image

In [4]:
cv2.namedWindow('image',cv2.WINDOW_NORMAL)

In [5]:
cv2.imshow('image',img)

In [6]:
cv2.waitKey(0)


27

In [7]:
cv2.imwrite('output_1.jpg',img)


True

In [8]:
ls

 Volume in drive C is Win10-L-R1-1803
 Volume Serial Number is 2E77-1B15

 Directory of C:\Users\AKATAM\Desktop\Linkedin Courses\OpenCV python

10/12/2019  08:45 PM    <DIR>          .
10/12/2019  08:45 PM    <DIR>          ..
10/12/2019  08:29 PM    <DIR>          .ipynb_checkpoints
10/12/2019  08:32 PM    <DIR>          Exercise files
10/12/2019  08:43 PM           219,764 OpenCV.pptx
10/12/2019  08:33 PM             1,023 OpenCV_Exercise.ipynb
10/12/2019  08:32 PM            24,903 opencv-logo.png
10/12/2019  08:45 PM            65,659 output_1.jpg
10/12/2019  08:28 PM                72 Untitled.ipynb
               5 File(s)        311,421 bytes
               4 Dir(s)  143,706,898,432 bytes free


In [7]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [8]:
type(img)

numpy.ndarray

In [11]:
len(img) #pixels    #number of rows

739

In [12]:
len(img[0])

600

In [14]:
len(img[0][0])  #number of channels

3

In [15]:
img.shape

(739, 600, 3)

In [16]:
img.dtype   #unsigned integer value

dtype('uint8')

In [17]:
#to access any pixel

img[10,5]

array([255, 255, 255], dtype=uint8)

In [18]:
#for accessing a single channel
img[:, :,0]         # 1st channel

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

739

In [36]:
img2=img[:, :,0]  #1st channel

In [22]:
cv2.namedWindow('image2',cv2.WINDOW_NORMAL)

In [25]:
cv2.imshow('image2',img2)

In [26]:
cv2.waitKey(0)

27

In [27]:
img3=img[:, :,1]  #2nd Channel

In [28]:
cv2.namedWindow('image3',cv2.WINDOW_NORMAL)

In [29]:
cv2.imshow('image3',img3)

In [30]:
cv2.waitKey(0)

27

In [37]:
img4=img[:, :,2] #3rd Channel

In [32]:
cv2.namedWindow('image4',cv2.WINDOW_FULLSCREEN)

In [33]:
cv2.imshow('image4',img4)

In [34]:
cv2.waitKey(0)

27

In [9]:
img.size   # total number of pixels

1330200

In [11]:
#generating initialized arrays

In [12]:
black= np.zeros([150,200,1],'uint8')

In [13]:
cv2.imshow('BLACK',black)

In [14]:
print(black[0,0,:])

[0]


In [15]:
cv2.waitKey(0)

27

In [16]:
cv2.destroyAllWindows()

In [17]:
black

array([[[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       ...,

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]]], dtype=uint8)

In [18]:
ones=np.ones([150,200,3],'uint8')

In [19]:
cv2.imshow('Ones',ones)

In [20]:
cv2.waitKey(0)

27

In [21]:
cv2.destroyAllWindows()

In [31]:
White=np.ones([150,200,3],'uint16')

In [33]:
White*=(2**16-1)

In [34]:
White

array([[[65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        ...,
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535]],

       [[65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        ...,
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535]],

       [[65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        ...,
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535]],

       ...,

       [[65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        ...,
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535]],

       [[65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        ...,
        [65535, 65535, 65535],
        [65535, 65535, 65535],
        [65535,

In [35]:
cv2.imshow('White',White)   #white image

In [36]:
cv2.waitKey(0)

27

In [38]:
cv2.destroyAllWindows()

In [154]:
colors= ones.copy()   # colored image

In [155]:
colors[:,:]= (255,0,0)

In [156]:
#cv2.namedWindow('Blue',cv2.WINDOW_NORMAL)

In [157]:
cv2.imshow('Blue',colors)

In [158]:
cv2.waitKey(0)

27

In [159]:
cv2.destroyAllWindows()

In [160]:
colors

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       ...,

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

In [161]:
#Image types and color channels

In [29]:
color_image=cv2.imread('butterfly.jpg',1)

In [30]:
cv2.imshow('Image',color_image)

In [31]:
cv2.moveWindow('Image',0,0)

In [32]:
height,width,channels=color_image.shape

In [33]:
height

356

In [35]:
cv2.waitKey(0)

27

In [9]:
cv2.destroyAllWindows()

In [10]:
#lets seee how individual channels look like

In [36]:
b,g,r=cv2.split(color_image)

In [37]:
color_image.shape

(356, 493, 3)

In [38]:
rgb_split= np.empty([height,width*3,3],'uint8')   # non initialized array matrix

In [39]:
rgb_split

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [40]:
rgb_split[:,0:width]=cv2.merge([b,b,b])

In [41]:
rgb_split[:,width:width*2]=cv2.merge([g,g,g])

In [42]:
rgb_split[:,width*2:width*3]=cv2.merge([r,r,r])

In [43]:
cv2.imshow('Channels',rgb_split)

In [44]:
cv2.moveWindow('Channels',0,height)

In [45]:
cv2.waitKey(0)

27

In [246]:
cv2.destroyAllWindows()

In [216]:
#using HSV    # Hue Saturation Luminosity

In [46]:
hsv= cv2.cvtColor(color_image,cv2.COLOR_BGR2HSV)

In [47]:
h,s,v=cv2.split(hsv)

In [48]:
h

array([[ 58,  58,  59, ..., 114, 124, 135],
       [ 58,  58,  59, ..., 119, 127, 138],
       [ 58,  58,  59, ..., 125, 134, 144],
       ...,
       [ 54,  55,  55, ...,  31,  33,  34],
       [ 54,  55,  55, ...,  31,  33,  34],
       [ 54,  55,  55, ...,  31,  33,  34]], dtype=uint8)

In [49]:
hsv_split=np.concatenate((h,s,v),axis=1)

In [50]:
cv2.imshow('Split HSV',hsv_split)

In [51]:
cv2.waitKey(0)

27

In [27]:
cv2.destroyAllWindows()

In [28]:
#Pixel manipulation and filtering

In [3]:
butterimage = cv2.imread('butterfly.jpg',1)

In [4]:
#converting to grayscale

In [5]:
gray=cv2.cvtColor(butterimage,cv2.COLOR_RGB2GRAY)

In [6]:
cv2.namedWindow('grayimage',cv2.WINDOW_NORMAL)

In [18]:
b=butterimage[:,:,0]
g=butterimage[:,:,1]
r=butterimage[:,:,2]

In [19]:
rgba=cv2.merge((b,g,r,g))

In [20]:
cv2.imwrite('rgba.png',rgba)

True

In [21]:
gray_image=cv2.imread('rgba.png',1)

In [22]:
cv2.namedWindow('gray_image',cv2.WINDOW_NORMAL)

In [23]:
cv2.imshow('gray_image',gray_image)

In [24]:
cv2.waitKey(0)

27

In [25]:
cv2.destroyAllWindows()

## Scaling and Rotating Images


In [28]:
player_img= cv2.imread('players.jpg',1)

In [29]:
Half_img= cv2.resize(player_img, (0,0), fx=0.5 , fy=0.5)
img_stretch=cv2.resize(player_img, (600,600))
img_stretch_near=cv2.resize(player_img,(600,600),interpolation=cv2.INTER_NEAREST)

In [30]:
cv2.imshow('HALF',Half_img)
cv2.imshow('Stretch',img_stretch)
cv2.imshow('Stretch near',img_stretch_near)

In [31]:
cv2.waitKey(0)

27

In [32]:
cv2.destroyAllWindows()

In [43]:
M= cv2.getRotationMatrix2D((0,0), -30, 1)
rotate=cv2.warpAffine(player_img, M, (player_img.shape[1], player_img.shape[0]))


In [47]:
cv2.imshow('ROTATE',rotate)

In [51]:
while(True):
    ch=cv2.waitKey(1)
    if ch & 0xFF == ord('0'):
        break

In [72]:
cv2.destroyAllWindows()

## Using video Inputs

In [53]:
cap =cv2.VideoCapture(0)

In [54]:
while(True):
    ret, frame= cap.read()
    frame=cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
    cv2.imshow('Frame',frame)
    ch=cv2.waitKey(1)
    if ch & 0xFF == ord('0'):
        break

cap.release()        
        

In [55]:
cv2.destroyAllWindows()

## Create Custom interfaces 

In [56]:
# we are going to draw a circle on the screen and place the circle wherever we click.


In [59]:
cap =cv2.VideoCapture(0)

color=(255,0,0)
point=(1,0)
radius=100
line_width=3


def click(event,x,y,flags,param):
    global point,pressed
    if event==cv2.EVENT_LBUTTONDOWN:
        print('pressed ',x,y)
        point=(x,y)
        
cv2.namedWindow('Frame')
cv2.setMouseCallback('Frame',click)



while(True):
    ret, frame= cap.read()
    frame=cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
    cv2.circle(frame,point,radius,color,line_width)
    cv2.imshow('Frame',frame)
    ch=cv2.waitKey(1)
    if ch & 0xFF == ord('0'):
        break

cap.release()        
        

pressed  185 129
pressed  136 110
pressed  105 87
pressed  268 84
pressed  130 78
pressed  88 211
pressed  228 231
pressed  272 24
pressed  102 39
pressed  48 139
pressed  258 200
pressed  145 67
pressed  78 187
pressed  211 210
pressed  131 94
pressed  268 62
pressed  178 123


In [102]:
cv2.destroyAllWindows()

# PROBLEM ON OPENCV

In [84]:
import numpy as np
import cv2

# Global variables
canvas = np.ones([500,500,3],'uint8')*255

color=(255,0,0)
point=(0,0)
radius=5
line_width=2
pressed= False


# click callback
def click(event, x, y, flags, param):
    global canvas,point,pressed
    if event == cv2.EVENT_LBUTTONDOWN:
        pressed =True
        point=(x,y)
        cv2.circle(canvas,point,radius,color,-1)
    elif event == cv2.EVENT_MOUSEMOVE and pressed == True:
        cv2.circle(canvas,point,radius,color,-1)
    elif event == cv2.EVENT_LBUTTONUP:
        pressed = False

# window initialization and callback assignment
cv2.namedWindow("canvas")
cv2.setMouseCallback("canvas", click)

# Forever draw loop
while True:
    #cv2.circle(canvas,point,radius,color2,line_width)
    cv2.imshow("canvas",canvas)
    # key capture every 1ms
    ch = cv2.waitKey(1)
    if ch & 0xFF == ord('q'):
        break
    elif ch & 0xFF == ord('g'):
        color=(0,255,0)
    elif ch & 0xFF == ord('r'):
        color=(0,0,255)    
    

cv2.destroyAllWindows()

# Canny edge detection

In [85]:
import numpy as np

In [86]:
import cv2

In [87]:
tomato= cv2.imread('tomatoes.jpg',1)

In [88]:
cv2.imshow('Tomatoes',tomato)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [90]:
hsv= cv2.cvtColor(tomato,cv2.COLOR_BGR2HSV)
res,thresh=cv2.threshold(hsv[:,:,0],25,255,cv2.THRESH_BINARY_INV)    # it extracts all values of hue less than or equal to 25.
cv2.imshow('Thresh',thresh)

edges= cv2.Canny(tomato,100,70)
cv2.imshow('Canny',edges)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Challenge

## Identify Large images and segment them , and each image should be drawn with its own color.

In [91]:
img_1=cv2.imread('fuzzy.png',1)

In [101]:
cv2.imshow('Original',img_1)
gray=cv2.cvtColor(img_1,cv2.COLOR_RGB2GRAY)
blur=cv2.GaussianBlur(gray,(3,3),0)
thresh=cv2.adaptiveThreshold(blur,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY_INV,205,1)
cv2.imshow('Binary',thresh)


# use contours
_, contours=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
print(len(contours))
filtered=[]
for c in contours:
    if cv2.contourArea(c) < 1000:continue
    filtered.append(c)
        
print(len(filtered))
cv2.waitKey(0)
cv2.destroyAllWindows()


1


error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:274: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'
